<div class="comment-box" id="cmtDiv_#cmtId" usefulCnt="#usefulCnt" isTop="#isTop" createTime="#cmtTime">
   <div class="userP">
     <img width="50px" height="50px" src="#avatar" alt="">
     <p class="text">#nickName</p>
    <!-- <p class="text">河南郑州</p> -->
   </div>
   <div class="cP">
     <div class="p-1">
       <div class="stars"><span style="width: #score%;"></span></div><span class="time fc-gray">#cmtTime</span>
     </div>
     <div class="p-2"><p>#cmtContent</p></div>
     <div class="p-3">
       这条评论对你有用吗？<a class="e-btn useful fulOrLess" href="javascript:void(0);" key="#cmtId" type="useful">有用</a><span id="useful_#cmtId" class="count">+#usefulCnt</span><a class="e-btn useless fulOrLess" href="javascript:void(0);" key="#cmtId" type="less">无用</a><span id="less_#cmtId" class="count">-#uselessCnt</span>
     </div>
     <div class="ui-arrow">
       <em>◆</em>
       <span>◆</span>
     </div>
    </div>
</div>
