</ol>
                </div>
            </div>
            <!--share-->
            <div class="share">
              <span class="fl">分享到：</span>
                <ul class="s-list clearfix">
                    <li><a href="javascript:;" class="site-sina" onclick="share_to('tsina');return false;" title="分享到新浪微博">新浪微博</a></li>
                    <li><a href="javascript:;" class="site-qq" onclick="share_to('qq');return false;" title="分享到给QQ好友">QQ</a></li>
                    <li><a href="javascript:;" class="site-qzone" onclick="share_to('tqq');return false;" title="分享到腾讯微博">腾讯微博</a></li>
                    <li><a href="javascript:;" class="site-renren" onclick="share_to('renren');return false;" title="分享到人人网">人人网</a></li>
                    <!--  <li><a href="javascript:;" class="site-kaixing" onclick="share_to('kaixin001');return false;" title="分享到开心网">开心网</a></li>
                    <li><a href="javascript:;" class="site-douban" onclick="share_to('douban');return false;" title="分享到豆瓣">豆瓣</a></li>
                    <li><a href="javascript:;" class="site-msn" onclick="share_to('live');return false;" title="分享给MSN好友">MSN</a></li>
                    <li><a href="javascript:;" class="site-email" title="邮件分享给好友">邮件</a></li> -->
                </ul>

            </div>
        </div>
    </div>

     <!--s6-->
    <div class="s6 fr">
      <div class="box favorable-suit" id="J-favorableSuit">
          <div class="hd">
                <h3 class="fc-red">优惠套餐</h3>
                <a class="btn btn-next fr" href="javascript:void (0);">后</a>
                <a class="btn btn-prev fr gap-mr10" href="javascript:void (0);">前</a>
            </div>
            <div class="bd">
                <div class="Jslide-bar clearfix">
                    <div class="bar-inner" id="taocanArea">

