<!--s1-->
<div class="s1 fl">
        <div class="box classify">
            <div class="hd">
                <h3>相关分类</h3>
            </div>
            <div class="bd">
                <ul class="clearfix"> 
                    #relationCategory
                </ul>
            </div>
        </div>
        <div class="box still">
            <div class="hd">
                <h3>浏览此商品的顾客购买了</h3>
            </div>
            <div class="bd">
                <div class="twP" id="leftRecDiv">
                   
                    #recommentInc
                    
                </div>
            </div>
        </div>
        <div class="box history">
            <div class="hd">
                <h3>最近浏览过的</h3>
            </div>
            <div class="bd">
                <div class="twP clearfix" id="historyDiv">
                  <!--  <ul class="twC">
                        <li class="pic"><a href="#"><img src="../images/img120x120.jpg" alt=""></a></li>
                        <li class="text title">
                            <h3><a href="#">进口食品东南亚美食越南特产波罗蜜干健康美味零食 250克</a></h3>
                        </li>
                        <li class="text price">
                            美丽价：<b class="fn-rmb fc-orange">&yen;299.00</b>
                        </li>
                    </ul>
                  -->
                </div>
            </div>
        </div>
        <div class="btnP">
            <a href="javascript:void(0);" onclick="MLW.history.product.clearHisPros('historyDiv');" class="anC4"><span>清除浏览记录</span></a>
        </div>
    </div>
</div>