            </div>
         </div>
      </div>
 </div>
  <!--优惠套餐end-->
<div class="product-detail">
        <a name="cmtArea"></a>
            <div class="Jtab" id="Jtab-main">
                <div class="Jtab-title-holder">
                    <div class="Jtab-title" id="Jtab-mainTitle">
                        <ul class="tab fl">
                            <li class="hover">商品详情</li>
                            <li id="cmtLi">商品评价</li>
                            <li>售后服务</li>
                        </ul>
                      
                        <div class="miniCart" id="J-miniCart">
                            <a class="anC8 fl"><span id="#miniCart" onclick="addProToCart();">加入购物车</span></a>
                            <div class="miniCart-list">
                                <div class="twP">
                                    <!--<p class="empty">空~~~</p>  -->
                                    <ul class="twC2">
                                        <li class="pic">
                                            <a href="#"><img id="miniProImg" src="" width="100px" height="100px" alt=""></a>
                                        </li>
                                        <li class="text">
                                            <h3 class="tt"><a href="#" id="miniProName"></a></h3>
                                            <p>美丽价:<b class="fn-rmb fc-red" id="miniProPrice"></b></p>
                                        </li>
                                    </ul>

                                </div>
                            </div>
                        </div>
                    
                    </div>
                </div>
                <div class="Jtab-content">
                    <div class="c1 content-cell current">
                         <!--锚点-->
                        <div class="anchor-box">
                            <div class="inn clearfix" id="J-anchor">
                              <!--  #anchorInfos
                                
                                -->
                            </div>
                        </div>
                        <!--锚点 end-->
                        <ul class="detail-list" id="propList">
                            #propList
                        </ul>
                        <div class="detail-content">
                            #propDescp
                        </div>
                        <div class="advisory">
                            <div class="Jtab" id="Jtab-advisory">
                                <div class="Jtab-title">
                                    <ul class="tab">
                                        <li class="hover">全部咨询（<span id="allConsult">#allCstNum</span>）</li>
                                        <li>商品咨询（<span id="proConsult">#1CstNum</span>）</li>
                                        <li>库存及配送（<span id="stockConsult">#2CstNum</span>）</li>
                                        <li>支付问题（<span id="payConsult">#3CstNum</span>）</li>
                                        <li>促销及赠品（<span id="promotionConsult">#4CstNum</span>）</li>
                                        <li>其他（<span id="otherConsult">#5CstNum</span>）</li>
                                    </ul>
                                </div>
                                <div class="Jtab-content">
                                    <p class="tip-welcome"><span class="gap-mr10">有问题？别藏着掖着啦！赶快问出来吧~~~我们的客服会尽快回复您的哦O(∩_∩)O~</span><a class="anC7" href="#" id="J-issue"><span>发表咨询</span></a></p>
                                    <div class="content-cell current">
                                        <ul class="grid-wrap clearfix" id="allCltUl">
                                            #allConsultContent
                                        </ul>
                                        <div class="page" >
                                            <div class="inner" id="allCltPage">
                                                
                                                <!--
                                                <a href="#" class="prev first">上一页</a><a href="#" class="on">1</a><a href="#">2</a><a href="#">3</a><a href="#">4</a><a href="#">5</a><span class="slh">...</span><a href="#">2000</a><a href="#" class="next">下一页</a><i>到第</i><input type="text" class="jump-to"><i>页</i><input type="submit" value="确定" class="jump">
                                                -->
                                            </div>
                                        </div>
                                    </div>
                                    <div class="content-cell">
                                        <ul class="grid-wrap clearfix" id="1CltUl">
                                            #1ConsultContent
                                        </ul>
                                        <div class="page">
                                            <div class="inner" id="1CltPage">
                                                
                                            </div>
                                        </div>
                                    </div>
                                    <div class="content-cell">
                                        <ul class="grid-wrap clearfix" id="2CltUl">
                                            #2ConsultContent
                                        </ul>
                                        <div class="page">
                                            <div class="inner" id="2CltPage">
                                                
                                            </div>
                                        </div>
                                    </div>
                                    <div class="content-cell">
                                        <ul class="grid-wrap clearfix" id="3CltUl">
                                           #3ConsultContent
                                        </ul>
                                        <div class="page">
                                            <div class="inner" id="3CltPage">
                                               
                                            </div>
                                        </div>
                                    </div>
                                    <div class="content-cell">
                                        <ul class="grid-wrap clearfix" id="4CltUl">
                                            #4ConsultContent
                                        </ul>
                                        <div class="page">
                                            <div class="inner" id="4CltPage">
                                                
                                            </div>
                                        </div>
                                    </div>
                                    <div class="content-cell">
                                        <ul class="grid-wrap clearfix" id="5CltUl">
                                           #5ConsultContent
                                        </ul>
                                        <div class="page">
                                            <div class="inner" id="5CltPage">
                                               
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>