                      <div class="slide-cube">
                        <div class="twP">
                                #pros
                                
                                <b class="equal"></b>
                                <ul class="twC infos" id="result_2">
                                    <li class="text title">
                                        <h3>#tcName</h3>
                                    </li>
                                    <li class="text price mlwP">
                                        美丽价：<b class="fn-rmb fc-red">¥#mlwPrice</b>
                                    </li>
                                    <li class="text"><del class="fl fn-rmb">原价：¥#originPrice</del></li>
                                    <li class="text price save">
                                        立即节省：<b class="fn-rmb fc-red">¥#savePrice</b>
                                    </li>
                                    <li class="buy"><a href="javascript:void(0);" onclick="addPackToCart(#tcId);" class="anC"><span>购买优惠套餐</span></a></li>
                                </ul>
                            </div>
                         </div>
