package com.gxems.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.10
 * 2014-03-04T11:56:40.001+08:00
 * Generated source version: 2.7.10
 * 
 */
@WebService(targetNamespace = "http://ws.gxems.com", name = "VipOrderIdBindingEmsNoWs")
public interface VipOrderIdBindingEmsNoWs {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "vipOrderIdBindingEmsNo", targetNamespace = "http://ws.gxems.com", className = "com.gxems.ws.VipOrderIdBindingEmsNo")
    @WebMethod
    @ResponseWrapper(localName = "vipOrderIdBindingEmsNoResponse", targetNamespace = "http://ws.gxems.com", className = "com.gxems.ws.VipOrderIdBindingEmsNoResponse")
    public String vipOrderIdBindingEmsNo(
            @WebParam(name = "validateKey", targetNamespace = "")
            String validateKey,
            @WebParam(name = "sender_CUST_Code", targetNamespace = "")
            String sender_CUST_Code,
            @WebParam(name = "orderIdList", targetNamespace = "")
            java.util.List<String> orderIdList,
            @WebParam(name = "emsnoList", targetNamespace = "")
            java.util.List<String> emsnoList
    );
}
